### PR TITLE
Added my own personal historical series about the history of everything before Bitcoin

### PR DESCRIPTION
**Pull request by pet3r-pan**
Added my own personal historical series about public key cryptography of the 70s (Hellman, Diffie, Merkle), origins of decentralisation in the 80s (David Chaum), the libertarian cryptowars of the 90s and also a part four perspective piece linking all of the past to the present.

### CODE REVIEW

**Comment by tombusby** [comment]
I will have a proper review of this. One thing you need to fix first though: if you look at "files changed" you'll see that you've actually removed an item as well as adding.

I've just skimmed your articles and they look very good. I look forward to reading them properly.

That said, it's quite likely I won't merge this PR, because I'm trying to avoid this list becoming unmanageably large.

I'm probably going to be restructuring the categories soon, so maybe I'll find a space for them. As for now, I'll leave this PR open.

**Comment by pet3r-pan** [comment]
If I removed an item, my bad. Fair enough. When I sent this in I could see it going both ways.

Enjoy the read :)

**Comment by tombusby** [comment]
I don't want to discourage you from contributing to the list though, and I may still find a spot for these. I'm not working directly on the list right now though because I'm working on a related project to properly parse the old mailing list archives.

**Comment by tombusby** [comment]
FYI, I've moved all the content in this repo to a dedicated site:

https://cryptoanarchy.wiki
https://twitter.com/_CryptoAnarchy

You can contribute here if you like:

https://github.com/cryptoanarchywiki/cryptoanarchywiki.github.io/

**Pull request closed without merging**
