### PR TITLE
Cypherpunks mailing list, notable ppl, orgs, prjs

### PR DESCRIPTION
**Pull request by gasull**
Added more notable cypherpunks from the original mailing list, some notable people, organizations, and projects.

### CODE REVIEW

**Comment by tombusby** [comment]
I haven't had a chance to look at this properly yet, but I will do soon. Thanks for the submission though. Some of these I can't believe I forgot to add in the first place.

**Comment by gasull** [comment]
I thought about adding Neal Stephenson, who was in the list too, but [he says he's not a cypherpunk](https://web.archive.org/web/20120406162502/http://web.mac.com:80/nealstephenson/Neal_Stephensons_Site/cypherFAQ.html):

> Is Neal Stephenson a cypherpunk?
> No. I read the list sometimes. But the Cypherpunks are a blend of mathematics and politics. I don't have enough knowldedge to talk about the math, and as an artist I consider myself obligated to avoid politics. 

Maybe a future change could be a sort of taxonomy:
- original cypherpunks from the mailing list, 
- cryptocurrency engineers (Satoshi, etc.),
- privacy activists (RMS, Aaron Swartz, Snowden, etc.),
- influential economists (David Friedman or, rather, Milton, who predicted cryptocurrency; SEK3; Rothbard).

**Comment by tombusby** [comment]
Ok, just a few thoughts here.

First one, as you can probably guess from the conversation we just had on twitter, I'm pretty resistent to adding Deadalnix. I just don't consider him notable. This is a cypherpunk history list, not a "people who currently have some presence or notoriety in the cryptocurrency space" list. If I added him, I'd have to add Bryce Weiner, and there's no way I'm doing that. Deadalnix hit fork on bitcoin/bitcoin and made some (relatively minor) changes, and his backers at Bitmain deployed them. I've already mentioned the major players in the Block Size Debate and I just don't think Deadalnix will be someone we remember in ten years. He's more of a pawn in that saga than a real player. His only major contribution was the EDA... and that was totally broken and had to be replaced.

RMS I actually explicitly made the decision not to include, because he's part of the broader Free Software Movement and I didn't want this (already broad) project getting too broad.

Bruce Scheier is someone who definitely should have been on there from the start. It's a major oversight of mine to leave him off.

Ryan Lackey I'm deffo on board with including.

Zooko I'll need to have a think about, and have a research into his past contributions prior to ZCash (because I don't want to just include the principle devs of a bunch of currencies and clutter up the list that way).

Matt Blaze I should probably include, even though ideologically he's very, very far from a lot of the ideals of the mailing list, but his notability for breaking the Clipper Chip is very high.

Aaron Swartz is definitely someone I might think about including. Again I have a similar problem determining people notable in "the cypherpunk movement and successor movements" and those who are notable in the broader "free sofware / hacker culture / etc".

Joanna Rutkowska I'll probably include, sure.

Some of the others you've added to the very notable section I'm not as familiar with, so I thank you for bringing them to my attention and I'll do some digging.

-----

> Maybe a future change could be a sort of taxonomy:

Completely agree with this and others have suggested similar changes.

> Is Neal Stephenson a cypherpunk?

Neal Stephenson should be on the list, because he probably wrote the only truly "cypherpunk" novels, and as mentioned on the main page, not everyone on here is a "cypherpunk". They just have to be notable within the cypherpunk movement (or successor movements - by which I almost entirely mean the cryptocurrency space really).

So yeah, when I have a mo, I'll do some digging on the others and get back to you.

**Comment by tombusby** [comment]
FYI, I've moved all the content in this repo to a dedicated site:

https://cryptoanarchy.wiki
https://twitter.com/_CryptoAnarchy

You can contribute here if you like:

https://github.com/cryptoanarchywiki/cryptoanarchywiki.github.io/

I will be taking on board the edits you made here. Hopefully tomorrow, I'll create pages for the people we agreed upon should be included.

**Comment by gasull** [comment]
> FYI, I've moved all the content in this repo to a dedicated site:
>  
> https://cryptoanarchy.wiki

That's a much better format.  :+1:

**Pull request closed without merging**
