### PR TITLE
Correct timelines

### PR DESCRIPTION
**Pull request by nopara73**
https://github.com/gavinandresen
  
  654 contributions in 2011
  742 contributions in 2012
  802 contributions in 2013
  336 contributions in 2014
  120 contributions in 2015
  46 contributions in 2016

### CODE REVIEW

**Comment by tombusby** [comment]
Hi, could you merge your repo from upstream? It looks like in the diff that merging this will undo some of the PRs I've just approved.

**Comment by tombusby** [comment]
I think I know what happened here actually. You had github's on-site editor open at the time I merged the PRs, so when you tried to submit your PR, you submitted the full original text (minus the changed I've just approved).

**Comment by tombusby** [comment]
Basically, not your mistake, just an unfortunate race-condition in the way github's on-site editor works.

**Comment by nopara73** [comment]
https://github.com/tombusby/cypherpunk-research/pull/10

**Pull request closed without merging**
